### ISSUE TITLE
cannot docker on arm7

### ISSUE THREAD

**Issue by Larthienn-mobile** [easimon/tado-exporter#18]
might be my issue, but i cannot for the love of my life make it work on my raspberry pi.

after going through docker step I am getting the following:

pi@raspberrypi:~/tado-exporter $ docker build . -t docker.pkg.github.com/easimon/tado-exporter/tado-exporter:latest
Sending build context to Docker daemon  573.4kB
Step 1/28 : ARG BUILD_IMAGE=openjdk:11
Step 2/28 : ARG TEST_IMAGE=adoptopenjdk/openjdk15:alpine
Step 3/28 : ARG RUNTIME_IMAGE=adoptopenjdk/openjdk15:alpine-jre
Step 4/28 : FROM $BUILD_IMAGE as builder
11: Pulling from library/openjdk
no matching manifest for linux/arm/v7 in the manifest list entries

let me know if I can help somehow in getting this version up there as well.

**Comment by easimon** [comment]
Openjdk does not offer armv7 images, at least not for the given tags. In the end, every JDK 11 or higher should work.

Will take a look into the options on the weekend.

**Comment by easimon** [comment]
Another quick shot: I currently do not have a Raspberry PI with 32 bit OS at hand, can you try the following on a Raspberry PI?

```
docker build \
  --build-arg BUILD_IMAGE=adoptopenjdk:11-hotspot \
  --build-arg TEST_IMAGE=adoptopenjdk:15-hotspot \
  --build-arg RUNTIME_IMAGE=adoptopenjdk:15-hotspot \
  -t docker.pkg.github.com/easimon/tado-exporter/tado-exporter:latest
```

For an unknown reason, the tests fail on Docker for Mac when using `docker buildx --platform linux/arm/v7`, but maybe they work on native Raspberry Pi. 

Anyway, having images available for other architectures is an interesting task, so this is something I will definitely look into. I just don't know when. Pull requests welcome :)

**Comment by Larthienn-mobile** [comment]
Hi Markus,

I will check asap when I when I will have some access to terminal.

Thanks for looking into this!

Pozdrawiam,
Kulecka Aleksandra,

**Comment by easimon** [comment]
That was easier than i thought. Please try 

```
docker run -e TADO_USERNAME=<your_username> -e TADO_PASSWORD=<your_password> ghcr.io/easimon/tado-exporter:3.0.0
```

No need to build yourself, or to log in to download the image anymore. Please note that the image location changed, because I switched from GitHub Packages to GitHub Container Registry.
