### ISSUE TITLE
Change 8080 webport

### ISSUE THREAD

**Issue by speeskeek** [easimon/tado-exporter#210]
Hi

I’ve been using another tado-github project - but it stopped functioning recently. 
I tried yours - I can compile, but it wont start (because port 8080 is in use, electricity monitoring). How can I change this please?

Keep up the great work!

**Comment by easimon** [comment]
It is Spring Boot. You should be able to change the port by e.g. setting the env variable `SERVER_PORT=7080`. Or any other way described here: https://www.baeldung.com/spring-boot-change-port

**Comment by speeskeek** [comment]
Super. Easy as that!
