### ISSUE TITLE
Feature Request: Home/Away status

### ISSUE THREAD

**Issue by bachirica** [easimon/tado-exporter#55]
First of all, thanks for this exporter!! I've been using it for a couple of weeks since I bought my new tado and works like a charm!!

Would it be possible to add the Home/Away status? I've seen it's available in the API and it would be really helpful on the dashboard I'm building with this.

Thanks!!

**Comment by easimon** [comment]
Seems like it was possible :)
Added with #56, release 5.1.0 is building as I write this.

**Comment by bachirica** [comment]
Awsome!! Just upgraded and added the home presence to my dashboard

![image](https://user-images.githubusercontent.com/25879955/200162413-84a2d8d0-5095-4f68-9438-d9ee1d7ff60b.png)

I'm no expert in Grafana but I can share the dashboard if you think it's useful to you.

![image](https://user-images.githubusercontent.com/25879955/200162603-b639fa31-df19-478c-afa1-7c59d56d8353.png)
